// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhncupqximauxrbndqbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhobmN1cHF4aW1hdXhyYm5kcWJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MzA5NzUsImV4cCI6MjA2NzAwNjk3NX0.4fsOoLq71dCCv92hw0zEe8sAwkNsqcRyxjSnNMqKlnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});